import { Listing } from "@/types";

// Mock data — to be replaced with Supabase
export const MOCK_LISTINGS: Listing[] = [
  {
    id: "1",
    category: "rubber",
    brand: "Butterfly",
    name: "Tenergy 05",
    pimple_type: "In",
    color: "Red",
    condition: "good",
    price: 28,
    description: "Utilisé 3 mois, encore beaucoup de grip. Idéal pour un joueur topspin.",
    seller: "Thomas M.",
    location: "Lyon",
    created_at: "2025-01-10",
    approval_code: "13-042",
  },
  {
    id: "2",
    category: "rubber",
    brand: "Tibhar",
    name: "Evolution MX-P",
    pimple_type: "In",
    color: "Black",
    condition: "like_new",
    price: 22,
    description: "2 semaines de test seulement, pas mon style de jeu. Parfait état.",
    seller: "Julien R.",
    location: "Paris",
    created_at: "2025-01-12",
    approval_code: "19-042",
  },
  {
    id: "3",
    category: "blade",
    brand: "Butterfly",
    name: "Timo Boll ALC",
    condition: "good",
    price: 65,
    description: "Bois 5 couches + 2 Arylate-Carbon. Quelques rayures légères sur la tranche, jeu impeccable.",
    seller: "Maryline T.",
    location: "Bordeaux",
    created_at: "2025-01-08",
  },
  {
    id: "4",
    category: "rubber",
    brand: "Donic",
    name: "Bluefire M1 Turbo",
    pimple_type: "In",
    color: "Red",
    condition: "like_new",
    price: 18,
    description: "Acheté en double, un de trop. Jamais joué.",
    seller: "Alexis B.",
    location: "Toulouse",
    created_at: "2025-01-14",
    approval_code: "06-053",
  },
  {
    id: "5",
    category: "rubber",
    brand: "Xiom",
    name: "Vega Europe",
    pimple_type: "In",
    color: "Black",
    condition: "fair",
    price: 9,
    description: "Bon revêtement d'initiation, encore très jouable. Prix imbattable pour débuter.",
    seller: "Camille D.",
    location: "Nantes",
    created_at: "2025-01-09",
  },
  {
    id: "6",
    category: "blade",
    brand: "Donic",
    name: "Waldner Senso Carbon",
    condition: "new",
    price: 55,
    description: "Neuf sous blister, cadeau reçu en double.",
    seller: "Pierre L.",
    location: "Lille",
    created_at: "2025-01-15",
  },
];
